language: node_js
node_js:
- 12
notifications:
  slack:
    secure: eN8yKZU3CuxEejuAJhiRXL1otPtlVf4d6ft3NnsAiEPeE6hdMjvlP9ixeftTWvOVOotayRMHpOls3PdLCq9rpIp3oPygJ0naeX/Zg5Q+eEKKQaB2NcIcWS9QLlk51Ebj14XMG74CgKoiDy27KkwBCjOn38SMBwUWqfXrgNx6wak6E1ImsbSkLOSr7REZDF4px2b2g8O4eoOBozZa6GVLxA3GX+WggwE/yv5xQRK7BFoEWfMc/amgyG2Pl0qpoGYvzaj8QKX7WMHejGkzrtw3Z6dlFxUFF8u3JimQ7rqeYVUnmDD2K0Q6JQv/7pgKd7jRHiR99X7YT1hQN2CJOx2/SErJ5a88/zc7T2v3sQr/gbG7WI1wTJOtAWndNsutNi5vHzSUjZjGVHbmHdFnbr/euERZ+x78BJuINnFuSXoon2GbmJ2s+KS/IIPGYdOh74dZQRLjUCJetpeYAZ2kuPZEXpYJQvR12zIVC0xWo8gK1TIfLu4fybxf8ZZPFmgoacznF7uwXLgkGFhB+jHYFLMfF5i6ZGSU+iHIn9TIJ7+cQBAUzKLVaTwbAdhAFFuhwV9oz+c++K+Hp84LZtymlCMEX+ZpJY2iJSMpY0RFTBdMgmP5Q2mqDMIjlqkUjPWVBsHnFKBXsagXnCQAojn/ymkg7q/RgaH6ZXQumhRph2MQ+uI=
